baseURL = "https://thenextbug.com/"
#baseURL = ""
languageCode = "en-us"
title = "The Next Bug"
theme = "hermit-V2"

googleAnalytics = "G-CZ0K1ZVCJ2"



[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.


[params.author]
  name = "Chris Salch"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "There's always another  one waiting around the corner."
  footerCopyright = '<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  custom_css = [ "css/extra.css" ]

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields


  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/The-Next-Bug"
  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/chris-salch-94a6784/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

