baseURL = "https://thenextbug.com/"
languageCode = "en-us"
title = "The Next Bug"
theme = "hermit"

[params]
  homeSubtitle = "There's always another  one waiting around the corner."

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/The-Next-Bug"
  [[params.social]]
    name = "linkedin"
    url = ""https://www.linkedin.com/in/chris-salch-94a6784/

